import Head from "next/head";
import { FC } from "react";

const Home: FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Index</h1>
    </div>
  );
};

export default Home;
